source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 8.1.2"
gem "bootsnap", require: false
gem "mysql2", "~> 0.5"
gem "puma"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.5"
gem "rack-cors"


group :development, :test do
  gem "debug"
  gem "rspec-rails"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 3.0"
end

group :development do
  gem "rubocop", "~> 1.50", require: false
  gem "rubocop-rails", "~> 2.17", require: false
end

group :test do
  gem "simplecov", "~> 0.22.0", require: false
  gem "shoulda-matchers", "~> 5.3"
end

